blank_issues_enabled: false
contact_links:
  - name: "Discussions / 讨论区"
    url: "https://github.com/rroy233/capyspeedtest/discussions"
    about: |
      General discussions and community help.
      一般讨论和社区帮助。
